#!/bin/busybox sh

rescue_shell() {
    echo "Something went wrong. Dropping you to a shell."
    busybox --install -s
    exec /bin/sh
}

# Prepare
mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys
echo 0 > /proc/sys/kernel/printk

# Unlock SSD (customize here)
cryptsetup luksOpen --allow-discards /dev/nvme0n1p3 root || rescue_shell

# Mount Root
mount -o ro /dev/mapper/root /mnt/ || rescue_shell 

# Clean up
echo 1 > /proc/sys/kernel/printk
umount /dev /proc /sys

# Switcheroo
exec switch_root /mnt /sbin/init
